__author__ = 'waldo'
from .vtnCliente import *
from .vtnAjusteNegativoStock import *
from .vtnMedicamento import *
from .vtnMonodroga import *
from .vtnPresentacion import *
from .vtnProducto import *
from .vtnLote import *
from .vtnRemito import *
from .vtnDevolucionDeCliente import *
from .vtnFraccionarProducto import *
from .vtnIngresar import *
from .vtnListar import *
from .vtnRegistrarCobroRemito import *
from .vtnReintegroCliente import *
from .vtnVentanaPrincipal import *
from .vtnVentaContado import *
from .vtnVentaConRemito import *
from .vtnTiposCobro import *
