# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'vtnFraccionarProducto.ui'
#
# Created: Sun Feb  7 14:20:12 2016
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_vtnFraccionarProducto(object):
    def setupUi(self, vtnFraccionarProducto):
        vtnFraccionarProducto.setObjectName(_fromUtf8("vtnFraccionarProducto"))
        vtnFraccionarProducto.resize(640, 479)
        self.verticalLayout = QtGui.QVBoxLayout(vtnFraccionarProducto)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gbProducto = QtGui.QGroupBox(vtnFraccionarProducto)
        self.gbProducto.setObjectName(_fromUtf8("gbProducto"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.gbProducto)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_2 = QtGui.QLabel(self.gbProducto)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout.addWidget(self.label_2)
        self.lineCod_Barra = QtGui.QLineEdit(self.gbProducto)
        self.lineCod_Barra.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.lineCod_Barra.setObjectName(_fromUtf8("lineCod_Barra"))
        self.horizontalLayout.addWidget(self.lineCod_Barra)
        self.btnBuscar = QtGui.QPushButton(self.gbProducto)
        self.btnBuscar.setFocusPolicy(QtCore.Qt.TabFocus)
        self.btnBuscar.setObjectName(_fromUtf8("btnBuscar"))
        self.horizontalLayout.addWidget(self.btnBuscar)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.tablaProducto = QtGui.QTableWidget(self.gbProducto)
        self.tablaProducto.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tablaProducto.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tablaProducto.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tablaProducto.setObjectName(_fromUtf8("tablaProducto"))
        self.tablaProducto.setColumnCount(5)
        self.tablaProducto.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tablaProducto.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tablaProducto.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tablaProducto.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tablaProducto.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tablaProducto.setHorizontalHeaderItem(4, item)
        self.tablaProducto.horizontalHeader().setDefaultSectionSize(160)
        self.tablaProducto.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_3.addWidget(self.tablaProducto)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_7 = QtGui.QLabel(self.gbProducto)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_6.addWidget(self.label_7)
        self.spinCantidad = QtGui.QSpinBox(self.gbProducto)
        self.spinCantidad.setMinimum(1)
        self.spinCantidad.setMaximum(100)
        self.spinCantidad.setSingleStep(1)
        self.spinCantidad.setObjectName(_fromUtf8("spinCantidad"))
        self.horizontalLayout_6.addWidget(self.spinCantidad)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.verticalLayout.addWidget(self.gbProducto)
        self.gbFraccionable = QtGui.QGroupBox(vtnFraccionarProducto)
        self.gbFraccionable.setObjectName(_fromUtf8("gbFraccionable"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.gbFraccionable)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.tablaFraccionable = QtGui.QTableWidget(self.gbFraccionable)
        self.tablaFraccionable.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tablaFraccionable.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tablaFraccionable.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tablaFraccionable.setObjectName(_fromUtf8("tablaFraccionable"))
        self.tablaFraccionable.setColumnCount(5)
        self.tablaFraccionable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tablaFraccionable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tablaFraccionable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tablaFraccionable.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tablaFraccionable.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tablaFraccionable.setHorizontalHeaderItem(4, item)
        self.tablaFraccionable.horizontalHeader().setDefaultSectionSize(160)
        self.tablaFraccionable.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_2.addWidget(self.tablaFraccionable)
        self.verticalLayout.addWidget(self.gbFraccionable)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.btnAceptar = QtGui.QPushButton(vtnFraccionarProducto)
        self.btnAceptar.setObjectName(_fromUtf8("btnAceptar"))
        self.horizontalLayout_5.addWidget(self.btnAceptar)
        self.btnCancelar = QtGui.QPushButton(vtnFraccionarProducto)
        self.btnCancelar.setObjectName(_fromUtf8("btnCancelar"))
        self.horizontalLayout_5.addWidget(self.btnCancelar)
        self.verticalLayout.addLayout(self.horizontalLayout_5)

        self.retranslateUi(vtnFraccionarProducto)
        QtCore.QMetaObject.connectSlotsByName(vtnFraccionarProducto)
        vtnFraccionarProducto.setTabOrder(self.lineCod_Barra, self.btnBuscar)
        vtnFraccionarProducto.setTabOrder(self.btnBuscar, self.tablaProducto)
        vtnFraccionarProducto.setTabOrder(self.tablaProducto, self.spinCantidad)
        vtnFraccionarProducto.setTabOrder(self.spinCantidad, self.tablaFraccionable)
        vtnFraccionarProducto.setTabOrder(self.tablaFraccionable, self.btnAceptar)
        vtnFraccionarProducto.setTabOrder(self.btnAceptar, self.btnCancelar)

    def retranslateUi(self, vtnFraccionarProducto):
        vtnFraccionarProducto.setWindowTitle(_translate("vtnFraccionarProducto", "Fraccionar Producto", None))
        self.gbProducto.setTitle(_translate("vtnFraccionarProducto", "Producto", None))
        self.label_2.setText(_translate("vtnFraccionarProducto", "Código de Barra", None))
        self.lineCod_Barra.setStatusTip(_translate("vtnFraccionarProducto", "Ingrese código de barra del Producto (exactamente 9 números)", None))
        self.lineCod_Barra.setAccessibleDescription(_translate("vtnFraccionarProducto", "codigo", None))
        self.btnBuscar.setText(_translate("vtnFraccionarProducto", "Buscar", None))
        item = self.tablaProducto.horizontalHeaderItem(0)
        item.setText(_translate("vtnFraccionarProducto", "Código de Barra", None))
        item = self.tablaProducto.horizontalHeaderItem(1)
        item.setText(_translate("vtnFraccionarProducto", "Medicamento", None))
        item = self.tablaProducto.horizontalHeaderItem(2)
        item.setText(_translate("vtnFraccionarProducto", "Presentación", None))
        item = self.tablaProducto.horizontalHeaderItem(3)
        item.setText(_translate("vtnFraccionarProducto", "Código de Lote", None))
        item = self.tablaProducto.horizontalHeaderItem(4)
        item.setText(_translate("vtnFraccionarProducto", "Cantidad", None))
        self.label_7.setText(_translate("vtnFraccionarProducto", "Cantidad", None))
        self.spinCantidad.setStatusTip(_translate("vtnFraccionarProducto", "Ingrese la cantidad del Producto para dicho lote", None))
        self.gbFraccionable.setTitle(_translate("vtnFraccionarProducto", "Fraccionable", None))
        item = self.tablaFraccionable.horizontalHeaderItem(0)
        item.setText(_translate("vtnFraccionarProducto", "Código de Barra", None))
        item = self.tablaFraccionable.horizontalHeaderItem(1)
        item.setText(_translate("vtnFraccionarProducto", "Medicamento", None))
        item = self.tablaFraccionable.horizontalHeaderItem(2)
        item.setText(_translate("vtnFraccionarProducto", "Presentación", None))
        item = self.tablaFraccionable.horizontalHeaderItem(3)
        item.setText(_translate("vtnFraccionarProducto", "Código de Lote", None))
        item = self.tablaFraccionable.horizontalHeaderItem(4)
        item.setText(_translate("vtnFraccionarProducto", "Cantidad", None))
        self.btnAceptar.setText(_translate("vtnFraccionarProducto", "Aceptar", None))
        self.btnCancelar.setText(_translate("vtnFraccionarProducto", "Cancelar", None))

