# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'vtnMedicamento.ui'
#
# Created: Sun Feb  7 13:33:22 2016
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_vtnMedicamento(object):
    def setupUi(self, vtnMedicamento):
        vtnMedicamento.setObjectName(_fromUtf8("vtnMedicamento"))
        vtnMedicamento.resize(552, 462)
        self.verticalLayout = QtGui.QVBoxLayout(vtnMedicamento)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gbMedicamento = QtGui.QGroupBox(vtnMedicamento)
        self.gbMedicamento.setObjectName(_fromUtf8("gbMedicamento"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.gbMedicamento)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_4 = QtGui.QLabel(self.gbMedicamento)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout.addWidget(self.label_4)
        self.lineNombre_Med = QtGui.QLineEdit(self.gbMedicamento)
        self.lineNombre_Med.setText(_fromUtf8(""))
        self.lineNombre_Med.setObjectName(_fromUtf8("lineNombre_Med"))
        self.horizontalLayout.addWidget(self.lineNombre_Med)
        self.btnBuscarMed = QtGui.QPushButton(self.gbMedicamento)
        self.btnBuscarMed.setFocusPolicy(QtCore.Qt.TabFocus)
        self.btnBuscarMed.setObjectName(_fromUtf8("btnBuscarMed"))
        self.horizontalLayout.addWidget(self.btnBuscarMed)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.tablaMedicamento = QtGui.QTableWidget(self.gbMedicamento)
        self.tablaMedicamento.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tablaMedicamento.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tablaMedicamento.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tablaMedicamento.setObjectName(_fromUtf8("tablaMedicamento"))
        self.tablaMedicamento.setColumnCount(3)
        self.tablaMedicamento.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tablaMedicamento.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tablaMedicamento.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tablaMedicamento.setHorizontalHeaderItem(2, item)
        self.tablaMedicamento.horizontalHeader().setDefaultSectionSize(160)
        self.tablaMedicamento.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_2.addWidget(self.tablaMedicamento)
        self.verticalLayout.addWidget(self.gbMedicamento)
        self.gbMonodroga = QtGui.QGroupBox(vtnMedicamento)
        self.gbMonodroga.setObjectName(_fromUtf8("gbMonodroga"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.gbMonodroga)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_5 = QtGui.QLabel(self.gbMonodroga)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_2.addWidget(self.label_5)
        self.lineNombre_Mon = QtGui.QLineEdit(self.gbMonodroga)
        self.lineNombre_Mon.setObjectName(_fromUtf8("lineNombre_Mon"))
        self.horizontalLayout_2.addWidget(self.lineNombre_Mon)
        self.btnBuscarMon = QtGui.QPushButton(self.gbMonodroga)
        self.btnBuscarMon.setObjectName(_fromUtf8("btnBuscarMon"))
        self.horizontalLayout_2.addWidget(self.btnBuscarMon)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.tablaMonodroga = QtGui.QTableWidget(self.gbMonodroga)
        self.tablaMonodroga.setEnabled(True)
        self.tablaMonodroga.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tablaMonodroga.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tablaMonodroga.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tablaMonodroga.setRowCount(0)
        self.tablaMonodroga.setObjectName(_fromUtf8("tablaMonodroga"))
        self.tablaMonodroga.setColumnCount(3)
        item = QtGui.QTableWidgetItem()
        self.tablaMonodroga.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tablaMonodroga.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tablaMonodroga.setHorizontalHeaderItem(2, item)
        self.tablaMonodroga.horizontalHeader().setDefaultSectionSize(140)
        self.tablaMonodroga.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_3.addWidget(self.tablaMonodroga)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_3 = QtGui.QLabel(self.gbMonodroga)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_8.addWidget(self.label_3)
        self.spinCantidad = QtGui.QSpinBox(self.gbMonodroga)
        self.spinCantidad.setMinimum(1)
        self.spinCantidad.setMaximum(10000000)
        self.spinCantidad.setSingleStep(10)
        self.spinCantidad.setObjectName(_fromUtf8("spinCantidad"))
        self.horizontalLayout_8.addWidget(self.spinCantidad)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.verticalLayout.addWidget(self.gbMonodroga)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.btnAceptar = QtGui.QPushButton(vtnMedicamento)
        self.btnAceptar.setObjectName(_fromUtf8("btnAceptar"))
        self.horizontalLayout_5.addWidget(self.btnAceptar)
        self.btnCancelar = QtGui.QPushButton(vtnMedicamento)
        self.btnCancelar.setObjectName(_fromUtf8("btnCancelar"))
        self.horizontalLayout_5.addWidget(self.btnCancelar)
        self.verticalLayout.addLayout(self.horizontalLayout_5)

        self.retranslateUi(vtnMedicamento)
        QtCore.QMetaObject.connectSlotsByName(vtnMedicamento)
        vtnMedicamento.setTabOrder(self.lineNombre_Med, self.btnBuscarMed)
        vtnMedicamento.setTabOrder(self.btnBuscarMed, self.tablaMedicamento)
        vtnMedicamento.setTabOrder(self.tablaMedicamento, self.lineNombre_Mon)
        vtnMedicamento.setTabOrder(self.lineNombre_Mon, self.btnBuscarMon)
        vtnMedicamento.setTabOrder(self.btnBuscarMon, self.tablaMonodroga)
        vtnMedicamento.setTabOrder(self.tablaMonodroga, self.spinCantidad)
        vtnMedicamento.setTabOrder(self.spinCantidad, self.btnAceptar)
        vtnMedicamento.setTabOrder(self.btnAceptar, self.btnCancelar)

    def retranslateUi(self, vtnMedicamento):
        vtnMedicamento.setWindowTitle(_translate("vtnMedicamento", "Alta Medicamento", None))
        self.gbMedicamento.setTitle(_translate("vtnMedicamento", "Medicamento", None))
        self.label_4.setText(_translate("vtnMedicamento", "Nombre", None))
        self.lineNombre_Med.setStatusTip(_translate("vtnMedicamento", "Ingrese nombre del medicamento (solo letrasy númros)", None))
        self.lineNombre_Med.setAccessibleDescription(_translate("vtnMedicamento", "textoNumeros", None))
        self.btnBuscarMed.setText(_translate("vtnMedicamento", "Buscar", None))
        item = self.tablaMedicamento.horizontalHeaderItem(0)
        item.setText(_translate("vtnMedicamento", "Nombre Comercial", None))
        item = self.tablaMedicamento.horizontalHeaderItem(1)
        item.setText(_translate("vtnMedicamento", "Monodroga", None))
        item = self.tablaMedicamento.horizontalHeaderItem(2)
        item.setText(_translate("vtnMedicamento", "Cantidad de Monodroga", None))
        self.gbMonodroga.setTitle(_translate("vtnMedicamento", "Monodroga", None))
        self.label_5.setText(_translate("vtnMedicamento", "* Nombre", None))
        self.lineNombre_Mon.setStatusTip(_translate("vtnMedicamento", "Ingrese nombre de la Monodroga", None))
        self.lineNombre_Mon.setAccessibleDescription(_translate("vtnMedicamento", "monodroga", None))
        self.btnBuscarMon.setText(_translate("vtnMedicamento", "Buscar", None))
        self.tablaMonodroga.setSortingEnabled(False)
        item = self.tablaMonodroga.horizontalHeaderItem(0)
        item.setText(_translate("vtnMedicamento", "Nombre", None))
        item = self.tablaMonodroga.horizontalHeaderItem(1)
        item.setText(_translate("vtnMedicamento", "Tipo de Venta", None))
        item = self.tablaMonodroga.horizontalHeaderItem(2)
        item.setText(_translate("vtnMedicamento", "Descripción", None))
        self.label_3.setText(_translate("vtnMedicamento", "Cantidad", None))
        self.spinCantidad.setStatusTip(_translate("vtnMedicamento", "Ingrese la cantidad del Producto para dicho lote", None))
        self.btnAceptar.setText(_translate("vtnMedicamento", "Aceptar", None))
        self.btnCancelar.setText(_translate("vtnMedicamento", "Cancelar", None))

