# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'vtnProducto.ui'
#
# Created: Tue Jan 19 19:46:37 2016
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_vtnProducto(object):
    def setupUi(self, vtnProducto):
        vtnProducto.setObjectName(_fromUtf8("vtnProducto"))
        vtnProducto.resize(749, 838)
        self.verticalLayout = QtGui.QVBoxLayout(vtnProducto)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gpProducto = QtGui.QGroupBox(vtnProducto)
        self.gpProducto.setFlat(False)
        self.gpProducto.setCheckable(False)
        self.gpProducto.setObjectName(_fromUtf8("gpProducto"))
        self.formLayout_4 = QtGui.QFormLayout(self.gpProducto)
        self.formLayout_4.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_4.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout_4.setObjectName(_fromUtf8("formLayout_4"))
        self.label_3 = QtGui.QLabel(self.gpProducto)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_3)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.lineCodigo_Barra = QtGui.QLineEdit(self.gpProducto)
        self.lineCodigo_Barra.setObjectName(_fromUtf8("lineCodigo_Barra"))
        self.horizontalLayout_3.addWidget(self.lineCodigo_Barra)
        self.btnBuscarProd = QtGui.QPushButton(self.gpProducto)
        self.btnBuscarProd.setObjectName(_fromUtf8("btnBuscarProd"))
        self.horizontalLayout_3.addWidget(self.btnBuscarProd)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.formLayout_4.setLayout(0, QtGui.QFormLayout.FieldRole, self.horizontalLayout_3)
        self.tablaProducto = QtGui.QTableWidget(self.gpProducto)
        self.tablaProducto.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tablaProducto.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tablaProducto.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tablaProducto.setObjectName(_fromUtf8("tablaProducto"))
        self.tablaProducto.setColumnCount(4)
        self.tablaProducto.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tablaProducto.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tablaProducto.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tablaProducto.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tablaProducto.setHorizontalHeaderItem(3, item)
        self.tablaProducto.horizontalHeader().setDefaultSectionSize(160)
        self.tablaProducto.horizontalHeader().setStretchLastSection(True)
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.SpanningRole, self.tablaProducto)
        self.label_4 = QtGui.QLabel(self.gpProducto)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_4)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.lineImporte = QtGui.QLineEdit(self.gpProducto)
        self.lineImporte.setInputMask(_fromUtf8(""))
        self.lineImporte.setObjectName(_fromUtf8("lineImporte"))
        self.horizontalLayout_6.addWidget(self.lineImporte)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.formLayout_4.setLayout(2, QtGui.QFormLayout.FieldRole, self.horizontalLayout_6)
        self.verticalLayout.addWidget(self.gpProducto)
        self.linea1 = QtGui.QFrame(vtnProducto)
        self.linea1.setFrameShape(QtGui.QFrame.HLine)
        self.linea1.setFrameShadow(QtGui.QFrame.Sunken)
        self.linea1.setObjectName(_fromUtf8("linea1"))
        self.verticalLayout.addWidget(self.linea1)
        self.gbMedicamento = QtGui.QGroupBox(vtnProducto)
        self.gbMedicamento.setObjectName(_fromUtf8("gbMedicamento"))
        self.formLayout_2 = QtGui.QFormLayout(self.gbMedicamento)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label_5 = QtGui.QLabel(self.gbMedicamento)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_5)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.lineNomb_Med = QtGui.QLineEdit(self.gbMedicamento)
        self.lineNomb_Med.setInputMask(_fromUtf8(""))
        self.lineNomb_Med.setObjectName(_fromUtf8("lineNomb_Med"))
        self.horizontalLayout.addWidget(self.lineNomb_Med)
        self.btnBuscarMed = QtGui.QPushButton(self.gbMedicamento)
        self.btnBuscarMed.setFocusPolicy(QtCore.Qt.TabFocus)
        self.btnBuscarMed.setObjectName(_fromUtf8("btnBuscarMed"))
        self.horizontalLayout.addWidget(self.btnBuscarMed)
        self.formLayout_2.setLayout(0, QtGui.QFormLayout.FieldRole, self.horizontalLayout)
        self.tablaMedicamento = QtGui.QTableWidget(self.gbMedicamento)
        self.tablaMedicamento.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tablaMedicamento.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tablaMedicamento.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tablaMedicamento.setObjectName(_fromUtf8("tablaMedicamento"))
        self.tablaMedicamento.setColumnCount(3)
        self.tablaMedicamento.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tablaMedicamento.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tablaMedicamento.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tablaMedicamento.setHorizontalHeaderItem(2, item)
        self.tablaMedicamento.horizontalHeader().setDefaultSectionSize(160)
        self.tablaMedicamento.horizontalHeader().setStretchLastSection(True)
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.SpanningRole, self.tablaMedicamento)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem2)
        self.btnActualizarMed = QtGui.QPushButton(self.gbMedicamento)
        self.btnActualizarMed.setObjectName(_fromUtf8("btnActualizarMed"))
        self.horizontalLayout_7.addWidget(self.btnActualizarMed)
        self.formLayout_2.setLayout(3, QtGui.QFormLayout.FieldRole, self.horizontalLayout_7)
        self.verticalLayout.addWidget(self.gbMedicamento)
        self.linea2 = QtGui.QFrame(vtnProducto)
        self.linea2.setFrameShape(QtGui.QFrame.HLine)
        self.linea2.setFrameShadow(QtGui.QFrame.Sunken)
        self.linea2.setObjectName(_fromUtf8("linea2"))
        self.verticalLayout.addWidget(self.linea2)
        self.gbPresentacion = QtGui.QGroupBox(vtnProducto)
        self.gbPresentacion.setObjectName(_fromUtf8("gbPresentacion"))
        self.formLayout_3 = QtGui.QFormLayout(self.gbPresentacion)
        self.formLayout_3.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.label_6 = QtGui.QLabel(self.gbPresentacion)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_6)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.lineTipo_Pres = QtGui.QLineEdit(self.gbPresentacion)
        self.lineTipo_Pres.setObjectName(_fromUtf8("lineTipo_Pres"))
        self.horizontalLayout_2.addWidget(self.lineTipo_Pres)
        self.btnBuscarPres = QtGui.QPushButton(self.gbPresentacion)
        self.btnBuscarPres.setFocusPolicy(QtCore.Qt.TabFocus)
        self.btnBuscarPres.setObjectName(_fromUtf8("btnBuscarPres"))
        self.horizontalLayout_2.addWidget(self.btnBuscarPres)
        self.formLayout_3.setLayout(1, QtGui.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.tablaPresentacion = QtGui.QTableWidget(self.gbPresentacion)
        self.tablaPresentacion.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tablaPresentacion.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tablaPresentacion.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tablaPresentacion.setObjectName(_fromUtf8("tablaPresentacion"))
        self.tablaPresentacion.setColumnCount(4)
        self.tablaPresentacion.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tablaPresentacion.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tablaPresentacion.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tablaPresentacion.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tablaPresentacion.setHorizontalHeaderItem(3, item)
        self.tablaPresentacion.horizontalHeader().setDefaultSectionSize(160)
        self.tablaPresentacion.horizontalHeader().setStretchLastSection(True)
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.SpanningRole, self.tablaPresentacion)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem3)
        self.btnActualizarPres = QtGui.QPushButton(self.gbPresentacion)
        self.btnActualizarPres.setObjectName(_fromUtf8("btnActualizarPres"))
        self.horizontalLayout_8.addWidget(self.btnActualizarPres)
        self.formLayout_3.setLayout(3, QtGui.QFormLayout.FieldRole, self.horizontalLayout_8)
        self.verticalLayout.addWidget(self.gbPresentacion)
        self.linea3 = QtGui.QFrame(vtnProducto)
        self.linea3.setFrameShape(QtGui.QFrame.HLine)
        self.linea3.setFrameShadow(QtGui.QFrame.Sunken)
        self.linea3.setObjectName(_fromUtf8("linea3"))
        self.verticalLayout.addWidget(self.linea3)
        self.gbLote = QtGui.QGroupBox(vtnProducto)
        self.gbLote.setObjectName(_fromUtf8("gbLote"))
        self.formLayout = QtGui.QFormLayout(self.gbLote)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.dateFechVenc = QtGui.QDateEdit(self.gbLote)
        self.dateFechVenc.setObjectName(_fromUtf8("dateFechVenc"))
        self.horizontalLayout_4.addWidget(self.dateFechVenc)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.formLayout.setLayout(2, QtGui.QFormLayout.FieldRole, self.horizontalLayout_4)
        self.label_2 = QtGui.QLabel(self.gbLote)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_2)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.spinCantidad = QtGui.QSpinBox(self.gbLote)
        self.spinCantidad.setMinimum(1)
        self.spinCantidad.setMaximum(500)
        self.spinCantidad.setSingleStep(10)
        self.spinCantidad.setObjectName(_fromUtf8("spinCantidad"))
        self.horizontalLayout_5.addWidget(self.spinCantidad)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem5)
        self.formLayout.setLayout(3, QtGui.QFormLayout.FieldRole, self.horizontalLayout_5)
        self.label_7 = QtGui.QLabel(self.gbLote)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_7)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.lineCod_Lote = QtGui.QLineEdit(self.gbLote)
        self.lineCod_Lote.setObjectName(_fromUtf8("lineCod_Lote"))
        self.horizontalLayout_12.addWidget(self.lineCod_Lote)
        self.btnBuscarLote = QtGui.QPushButton(self.gbLote)
        self.btnBuscarLote.setFocusPolicy(QtCore.Qt.TabFocus)
        self.btnBuscarLote.setObjectName(_fromUtf8("btnBuscarLote"))
        self.horizontalLayout_12.addWidget(self.btnBuscarLote)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem6)
        self.formLayout.setLayout(0, QtGui.QFormLayout.FieldRole, self.horizontalLayout_12)
        self.label = QtGui.QLabel(self.gbLote)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.verticalLayout.addWidget(self.gbLote)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem7)
        self.btnAceptar = QtGui.QPushButton(vtnProducto)
        self.btnAceptar.setObjectName(_fromUtf8("btnAceptar"))
        self.horizontalLayout_11.addWidget(self.btnAceptar)
        self.btnCancelar = QtGui.QPushButton(vtnProducto)
        self.btnCancelar.setObjectName(_fromUtf8("btnCancelar"))
        self.horizontalLayout_11.addWidget(self.btnCancelar)
        self.verticalLayout.addLayout(self.horizontalLayout_11)

        self.retranslateUi(vtnProducto)
        QtCore.QMetaObject.connectSlotsByName(vtnProducto)
        vtnProducto.setTabOrder(self.lineCodigo_Barra, self.btnBuscarProd)
        vtnProducto.setTabOrder(self.btnBuscarProd, self.tablaProducto)
        vtnProducto.setTabOrder(self.tablaProducto, self.lineImporte)
        vtnProducto.setTabOrder(self.lineImporte, self.lineNomb_Med)
        vtnProducto.setTabOrder(self.lineNomb_Med, self.btnBuscarMed)
        vtnProducto.setTabOrder(self.btnBuscarMed, self.tablaMedicamento)
        vtnProducto.setTabOrder(self.tablaMedicamento, self.btnActualizarMed)
        vtnProducto.setTabOrder(self.btnActualizarMed, self.lineTipo_Pres)
        vtnProducto.setTabOrder(self.lineTipo_Pres, self.btnBuscarPres)
        vtnProducto.setTabOrder(self.btnBuscarPres, self.tablaPresentacion)
        vtnProducto.setTabOrder(self.tablaPresentacion, self.btnActualizarPres)
        vtnProducto.setTabOrder(self.btnActualizarPres, self.lineCod_Lote)
        vtnProducto.setTabOrder(self.lineCod_Lote, self.btnBuscarLote)
        vtnProducto.setTabOrder(self.btnBuscarLote, self.dateFechVenc)
        vtnProducto.setTabOrder(self.dateFechVenc, self.spinCantidad)
        vtnProducto.setTabOrder(self.spinCantidad, self.btnAceptar)
        vtnProducto.setTabOrder(self.btnAceptar, self.btnCancelar)

    def retranslateUi(self, vtnProducto):
        vtnProducto.setWindowTitle(_translate("vtnProducto", "Alta Producto", None))
        self.gpProducto.setTitle(_translate("vtnProducto", "Producto", None))
        self.label_3.setText(_translate("vtnProducto", "Código de Barra", None))
        self.lineCodigo_Barra.setStatusTip(_translate("vtnProducto", "Ingrese código de barra del producto (exactamente 9 números)", None))
        self.lineCodigo_Barra.setAccessibleDescription(_translate("vtnProducto", "codigo", None))
        self.btnBuscarProd.setText(_translate("vtnProducto", "Buscar", None))
        item = self.tablaProducto.horizontalHeaderItem(0)
        item.setText(_translate("vtnProducto", "Código de Barra", None))
        item = self.tablaProducto.horizontalHeaderItem(1)
        item.setText(_translate("vtnProducto", "Medicamento", None))
        item = self.tablaProducto.horizontalHeaderItem(2)
        item.setText(_translate("vtnProducto", "Presentación", None))
        item = self.tablaProducto.horizontalHeaderItem(3)
        item.setText(_translate("vtnProducto", "Importe", None))
        self.label_4.setText(_translate("vtnProducto", "Importe $", None))
        self.lineImporte.setStatusTip(_translate("vtnProducto", "Ingrese importe del producto (solo números separando los centavos por un punto (.) ejemplo 125.75)", None))
        self.lineImporte.setAccessibleDescription(_translate("vtnProducto", "importe", None))
        self.gbMedicamento.setTitle(_translate("vtnProducto", "Medicamento", None))
        self.label_5.setText(_translate("vtnProducto", "Nombre Comercial", None))
        self.lineNomb_Med.setStatusTip(_translate("vtnProducto", "Ingrese nombre del Medicamento (solo números y letras)", None))
        self.lineNomb_Med.setAccessibleDescription(_translate("vtnProducto", "textoNumeros", None))
        self.btnBuscarMed.setText(_translate("vtnProducto", "Buscar", None))
        item = self.tablaMedicamento.horizontalHeaderItem(0)
        item.setText(_translate("vtnProducto", "Nombre Comercial", None))
        item = self.tablaMedicamento.horizontalHeaderItem(1)
        item.setText(_translate("vtnProducto", "Monodroga", None))
        item = self.tablaMedicamento.horizontalHeaderItem(2)
        item.setText(_translate("vtnProducto", "Cantidad de Monodroga", None))
        self.btnActualizarMed.setText(_translate("vtnProducto", "Actualizar", None))
        self.gbPresentacion.setTitle(_translate("vtnProducto", "Presentación", None))
        self.label_6.setText(_translate("vtnProducto", "Tipo", None))
        self.lineTipo_Pres.setStatusTip(_translate("vtnProducto", "Ingrese tipo de presentación(solo letras)", None))
        self.lineTipo_Pres.setAccessibleDescription(_translate("vtnProducto", "texto", None))
        self.btnBuscarPres.setText(_translate("vtnProducto", "Buscar", None))
        item = self.tablaPresentacion.horizontalHeaderItem(0)
        item.setText(_translate("vtnProducto", "Tipo", None))
        item = self.tablaPresentacion.horizontalHeaderItem(1)
        item.setText(_translate("vtnProducto", "Cantidad de Fracciones", None))
        item = self.tablaPresentacion.horizontalHeaderItem(2)
        item.setText(_translate("vtnProducto", "Unidad de Medida", None))
        item = self.tablaPresentacion.horizontalHeaderItem(3)
        item.setText(_translate("vtnProducto", "Fraccionable", None))
        self.btnActualizarPres.setText(_translate("vtnProducto", "Actualizar", None))
        self.gbLote.setTitle(_translate("vtnProducto", "Lote", None))
        self.label_2.setText(_translate("vtnProducto", "Fecha de Vencimiento", None))
        self.spinCantidad.setStatusTip(_translate("vtnProducto", "Ingrese la cantidad del Producto para dicho lote", None))
        self.label_7.setText(_translate("vtnProducto", "Cantidad", None))
        self.lineCod_Lote.setStatusTip(_translate("vtnProducto", "Ingrese código del lote (solo letras y números sin espacios)", None))
        self.lineCod_Lote.setAccessibleDescription(_translate("vtnProducto", "codLote", None))
        self.btnBuscarLote.setText(_translate("vtnProducto", "Buscar", None))
        self.label.setText(_translate("vtnProducto", "Código", None))
        self.btnAceptar.setText(_translate("vtnProducto", "Aceptar", None))
        self.btnCancelar.setText(_translate("vtnProducto", "Cancelar", None))

